services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=coldlogistics"
      - "POSTGRES_PASSWORD=Pass1234"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432"
